spring.application.name=spring-demo

#DEFAULT DATABASE SETTINGS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#STAND DATABASE SETTINGS
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo_example?currentSchema=spring_demo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
