DROP TABLE IF EXISTS ALBUM;
CREATE TABLE IF NOT EXISTS ALBUM
(
    ID BIGINT NOT NULL DEFAULT nextval('seq_album'),
    SINGER_ID BIGINT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    RELEASE_DATE DATE,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATE_MOMENT TIMESTAMP WITH TIME ZONE,
    UPDATE_MOMENT TIMESTAMP WITH TIME ZONE,
                                PRIMARY KEY (ID),
    UNIQUE (SINGER_ID, TITLE),
    CONSTRAINT FK_ALBUM_SINGER FOREIGN KEY (SINGER_ID)
    REFERENCES SINGER (ID)
);