DROP TABLE IF EXISTS SINGER;
CREATE TABLE IF NOT EXISTS SINGER
(
    ID BIGINT NOT NULL DEFAULT nextval('seq_singer'),
    FIRST_NAME VARCHAR(60) NOT NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    BIRTH_DATE DATE,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATE_MOMENT TIMESTAMP WITH TIME ZONE,
    UPDATE_MOMENT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (ID),
    UNIQUE (FIRST_NAME, LAST_NAME)
);