DROP TABLE IF EXISTS SINGER_INSTRUMENT;
CREATE TABLE IF NOT EXISTS SINGER_INSTRUMENT
(
    SINGER_ID BIGINT NOT NULL,
    INSTRUMENT_ID BIGINT NOT NULL,
    PRIMARY KEY (SINGER_ID, INSTRUMENT_ID),
    CONSTRAINT FK_SINGER_INSTRUMENT_1
        FOREIGN KEY (SINGER_ID)
            REFERENCES SINGER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SINGER_INSTRUMENT_2
        FOREIGN KEY (INSTRUMENT_ID)
            REFERENCES INSTRUMENT (ID)
);